---
- name: Configure Webserver
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure webserver is updated
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      notify:
        - Start Nginx

  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

- name: Configure DBserver
  hosts: dbservers
  become: yes
  tasks:
    - name: Ensure dbserver is updated
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      notify:
        - Start MySQL
    
    - name: Set MySQL root password
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "mossad1234" 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_password_length: no
        check_implicit_privs: no 
      no_log: true

  handlers:
    - name: Start MySQL
      service:
        name: mysql
        state: started
        enabled: yes